### PR TITLE
New src dir

### PR DESCRIPTION
**Pull request by LenkaNovak**
Re-organised scripts and notebooks in the src, added more up-to-date versions.

### CODE REVIEW

**Comment by jiahe23** [comment]
@charleskawczynski Could you take a look at the codecov report here? Do we still need it?

**Review by bischtob — APPROVED** [review]

**Comment by charleskawczynski** [comment]
> Could you take a look at the codecov report here? Do we still need it?

Codecov is not necessary to pass for the PR to merge, so this should be fine

**Review by charleskawczynski — COMMENTED** [review]
Should we delete all of the `.ipynb_checkpoints` while we're at it? Also, we should probably add `.ipynb_checkpoints` to the `.gitignore`

**Pull request merged**
